CarMaintenance/Models/Services.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CarMaintenance.Models
{
    public class Services
    {
        [Key]
        public int ServiceID { get; set; }

        public string ServiceName { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }

        public int ServiceStatus { get; set; }

        // Navigation
        [ValidateNever]
        public ICollection<ReceiptsDetails> ReceiptsDetails { get; set; }

    }
}

CarMaintenance/Controllers/ServicesController.cs
using CarMaintenance.Data;
using CarMaintenance.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarMaintenance.Controllers
{
    public class ServicesController : Controller
    {
        private AppDbContext db;

        public ServicesController(AppDbContext _db)
        {
            db = _db;
        }

        public IActionResult Index()
        {
            var data = db.Tbl_Services;
            return View(data);
        }

        public IActionResult AddService()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddService(Services services)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Services.Add(services);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult EditService(int Id)
        {
            var data = db.Tbl_Services.Find(Id);
            return View(data);
        }

        [HttpPost]
        public IActionResult EditService(Services services)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Services.Update(services);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult DeleteService(int Id)
        {
            var data = db.Tbl_Services.Find(Id);

            if (data != null)
            {
                db.Tbl_Services.Remove(data);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

CarMaintenance/Views/Services/AddService.cshtml
@model Services
@inject IViewLocalizer Localizer
@using CarMaintenance
@inject Microsoft.Extensions.Localization.IStringLocalizer<SharedResource> Localizer

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@Localizer["AddServiceTitle"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">@Localizer["HomeLink"]</a></li>
                    <li class="breadcrumb-item active">@Localizer["ServicesBreadcrumb"]</li>
                </ol>
            </div>
        </div>
        <hr />
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="container">
        <form method="post" asp-action="AddService" asp-controller="Services">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div> <!-- Added validation summary -->
            <div class="row my-2">
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="ServiceName">@Localizer["ServiceNameLabel"]</label>
                    <input class="form-control" asp-for="ServiceName" />
                    <span class="text-danger" asp-validation-for="ServiceName"></span>
                </div>
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="Description">@Localizer["DescriptionLabel"]</label>
                    <input class="form-control" asp-for="Description" />
                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="Price">@Localizer["PriceLabel"]</label>
                    <input class="form-control" asp-for="Price" />
                    <span class="text-danger" asp-validation-for="Price"></span>
                </div>
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="ServiceStatus" hidden>@Localizer["ServiceStatusLabel"]</label>
                    <input class="form-control" asp-for="ServiceStatus" value="1" hidden />
                    <span class="text-danger" asp-validation-for="ServiceStatus" hidden></span>
                </div>
                <div class="col-md-12 my-2">
                    <button type="submit" class="btn btn-primary">@Localizer["AddServiceButton"]</button>
                </div>
            </div>
        </form>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" /> <!-- Include validation scripts -->
}

CarMaintenance/Views/Services/EditService.cshtml
@model Services
@inject IViewLocalizer Localizer
@using CarMaintenance
@inject Microsoft.Extensions.Localization.IStringLocalizer<SharedResource> Localizer

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@Localizer["UpdateServiceTitle"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">@Localizer["HomeLink"]</a></li>
                    <li class="breadcrumb-item active">@Localizer["ServicesBreadcrumb"]</li>
                </ol>
            </div>
        </div>
        <hr />
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="container">
        <form method="post" asp-action="EditService" asp-controller="Services">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div> <!-- Added validation summary -->
            <div class="row my-2">
                <input asp-for="ServiceID" hidden />
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="ServiceName">@Localizer["ServiceNameLabel"]</label>
                    <input class="form-control" asp-for="ServiceName" />
                    <span class="text-danger" asp-validation-for="ServiceName"></span>
                </div>
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="Description">@Localizer["DescriptionLabel"]</label>
                    <input class="form-control" asp-for="Description" />
                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="Price">@Localizer["PriceLabel"]</label>
                    <input class="form-control" asp-for="Price" />
                    <span class="text-danger" asp-validation-for="Price"></span>
                </div>
                <div class="col-md-6 form-group">
                    <label class="form-label" asp-for="ServiceStatus" hidden>@Localizer["ServiceStatusLabel"]</label>
                    <input class="form-control" asp-for="ServiceStatus" value="1" hidden />
                    <span class="text-danger" asp-validation-for="ServiceStatus" hidden></span>
                </div>
                <div class="col-md-12 my-2">
                    <button type="submit" class="btn btn-primary">@Localizer["UpdateServiceButton"]</button>
                </div>
            </div>
        </form>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" /> <!-- Include validation scripts -->
}

CarMaintenance/Views/Services/Index.cshtml
@model IEnumerable<Services>
@inject IViewLocalizer Localizer
@inject Microsoft.Extensions.Localization.IStringLocalizer<SharedResource> Localizer
@using CarMaintenance
@using System.Globalization

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@Localizer["ViewServicesTitle"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">@Localizer["HomeLink"]</a></li>
                    <li class="breadcrumb-item active">@Localizer["ServicesBreadcrumb"]</li>
                </ol>
            </div>
        </div>
        <hr />
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <a class="btn btn-primary my-3" asp-action="AddService" asp-controller="Services">@Localizer["AddServiceButton"]</a>
            </h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>@Localizer["ServiceID"]</th>
                        <th>@Localizer["ServiceName"]</th>
                        <th>@Localizer["Description"]</th>
                        <th>@Localizer["Price"]</th>
                        <th>@Localizer["Edit"]</th>
                        <th>@Localizer["Delete"]</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Any())
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@item.ServiceID</th>
                                <td>@item.ServiceName</td>
                                <td>@item.Description</td>
                                <td>@item.Price</td>
                                <td><p><a class="text-primary fas fa-pen" asp-action="EditService" asp-controller="Services" asp-route-Id="@item.ServiceID"></a></p></td>
                                <td><p><a class="text-danger fas fa-trash" asp-action="DeleteService" asp-controller="Services" asp-route-Id="@item.ServiceID"></a></p></td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td class="text-center" colspan="6">@Localizer["NoRecordFound"]</td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>@Localizer["ServiceID"]</th>
                        <th>@Localizer["ServiceName"]</th>
                        <th>@Localizer["Description"]</th>
                        <th>@Localizer["Price"]</th>
                        <th>@Localizer["Edit"]</th>
                        <th>@Localizer["Delete"]</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
</section>

@section Scripts {
    <!-- DataTables & Plugins -->
    <script src="~/AdminTheme/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/AdminTheme/plugins/jszip/jszip.min.js"></script>
    <script src="~/AdminTheme/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/AdminTheme/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <!-- Page specific script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "language": {
                    "url": "@(CultureInfo.CurrentCulture.Name == "ar-SA" ? "//cdn.datatables.net/plug-ins/1.13.6/i18n/ar.json" : "//cdn.datatables.net/plug-ins/1.13.6/i18n/en-GB.json")"
                },
                "buttons": [
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: [0, 1, 2, 3]
                        }
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: [0, 1, 2, 3]
                        }
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [0, 1, 2, 3]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [0, 1, 2, 3]
                        }
                    },
                    {
                        extend: 'print',
                        text: '@Localizer["PrintButton"]',
                        title: '',
                        exportOptions: {
                            columns: [0, 1, 2, 3]
                        },
                        customize: function (win) {
                            $(win.document.body).prepend(
                                '<div style="display:flex; justify-content:space-between; margin-bottom:20px;">' +
                                '<h2 style="margin:0;">@Localizer["ServicesReport"]</h2>' +
                                '<img src="/images/logo1.png" style="height:60px;" />' +
                                '</div>'
                            );

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', '12px')
                                .css('width', '100%');
                        }
                    },
                    "colvis"
                ]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });
    </script>
}