CarMaintenance/Models/TransferCars.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarMaintenance.Models
{
    public class TransferCars
    {
        [Key]
        public int TransferID { get; set; }

        public DateTime TransferDate { get; set; } = DateTime.Now;

        public int FromCustomerID { get; set; }

        [ForeignKey("FromCustomerID")]
        public Customers? FromCustomers { get; set; }

        public int ToCustomerID { get; set; }

        [ForeignKey("ToCustomerID")]
        public Customers? ToCustomers { get; set; }

        public int CarID { get; set; }

        [ForeignKey("CarID")]
        public Cars? Cars { get; set; }

    }
}

CarMaintenance/Controllers/TransferCarsController.cs
using CarMaintenance.Data;
using CarMaintenance.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CarMaintenance.Controllers
{
    public class TransferCarsController : Controller
    {
        private AppDbContext db;

        public TransferCarsController(AppDbContext _db)
        {
            db = _db;
        }

        public IActionResult Index()
        {
            var data = db.Tbl_TransferCars.Include(x => x.FromCustomers).Include(y => y.ToCustomers).Include(z => z.Cars).ToList();

            return View(data);
        }

        public IActionResult Transfer()
        {
            ViewBag.Customers = new SelectList(db.Tbl_Customers.Where(x => x.CarID != 0).ToList(), "CustomerID", "Name");

            var model = new TransferCars
            {
                TransferDate = DateTime.Now
            };

            return View(model);

        }

        [HttpGet]
        public IActionResult GetCarByCustomer(int customerId)
        {
            var car = db.Tbl_Customers
                        .Where(c => c.CustomerID == customerId)
                        .Select(c => new
                        {
                            c.CarID,
                            c.Cars.NumberPlate // Adjust this property name if different
                        }).FirstOrDefault();

            return Json(car);
        }

        [HttpPost]
        public IActionResult Transfer(TransferCars model)
        {
            if (ModelState.IsValid)
            {
                var fromCustomer = db.Tbl_Customers.Find(model.FromCustomerID);
                var toCustomer = db.Tbl_Customers.Find(model.ToCustomerID);

                if (fromCustomer != null && toCustomer != null)
                {
                    // 1. Update old customer’s CarID to 0
                    fromCustomer.CarID = null;


                    // 2. Assign the car to the new customer
                    toCustomer.CarID = model.CarID;

                    // 3. Save transfer record
                    db.Tbl_TransferCars.Add(model);

                    db.SaveChanges();

                    TempData["success"] = "Car transferred successfully.";
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Customers = new SelectList(db.Tbl_Customers.ToList(), "CustomerID", "Name");
            return View(model);
        }



    }
}

CarMaintenance/Views/TransferCars/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model IEnumerable<TransferCars>
@inject Microsoft.Extensions.Localization.IStringLocalizer<SharedResource> Localizer
@using System.Globalization

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@Localizer["TransferNumberPlateTitle"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">@Localizer["Home"]</a></li>
                    <li class="breadcrumb-item active">@Localizer["TransferCarsTitle"]</li>
                </ol>
            </div>
        </div>
        <hr />
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <a class="btn btn-primary my-3" asp-action="Transfer" asp-controller="TransferCars">
                    @Localizer["TransferNewNumberPlate"]
                </a>
            </h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>@Localizer["ID"]</th>
                        <th>@Localizer["DateLabel"]</th>
                        <th>@Localizer["From"]</th>
                        <th>@Localizer["To"]</th>
                        <th>@Localizer["NumberPlate"]</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Any())
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@item.TransferID</th>
                                <td>@item.TransferDate</td>
                                <td>@item.FromCustomers?.Name</td>
                                <td>@item.ToCustomers?.Name</td>
                                <td>@item.Cars?.NumberPlate</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td class="text-center" colspan="5">@Localizer["NoRecordFound"]</td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>@Localizer["ID"]</th>
                        <th>@Localizer["Date"]</th>
                        <th>@Localizer["From"]</th>
                        <th>@Localizer["To"]</th>
                        <th>@Localizer["NumberPlate"]</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
</section>

@section Scripts {
    <!-- DataTables & Plugins -->
    <script src="~/AdminTheme/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/AdminTheme/plugins/jszip/jszip.min.js"></script>
    <script src="~/AdminTheme/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/AdminTheme/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/AdminTheme/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <!-- Page specific script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "url": "/i18n/datatables/@System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName".json"
                }
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });
    </script>
}

CarMaintenance/Views/TransferCars/Transfer.cshtml
@model TransferCars
@inject IViewLocalizer Localizer
@using CarMaintenance
@inject Microsoft.Extensions.Localization.IStringLocalizer<SharedResource> Localizer
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@Localizer["TransferCarsTitle"]</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">@Localizer["Home"]</a></li>
                    <li class="breadcrumb-item active">@Localizer["TransferCars"]</li>
                </ol>
            </div>
        </div>
        <hr />
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="container">
        <form method="post" asp-action="Transfer" asp-controller="TransferCars">
            <div class="row my-2">

                <div class="col-md-6 form-group">
                    <label class="form-label">
                        @Localizer["From"]
                        <span class="text-danger fw-bold" asp-validation-for="FromCustomerID"></span>
                    </label>
                    <select class="form-control" asp-for="FromCustomerID" asp-items="ViewBag.Customers">
                        <option value="">@Localizer["SelectCustomer"]</option>
                    </select>
                </div>

                <div class="col-md-6 form-group">
                    <label class="form-label">@Localizer["NumberPlate"]</label>
                    <input class="form-control" id="NumberPlate" readonly />
                    <input type="hidden" id="CarID" name="CarID" asp-for="CarID" />
                </div>

                <div class="col-md-6 form-group">
                    <label class="form-label">
                        @Localizer["To"]
                        <span class="text-danger fw-bold" asp-validation-for="ToCustomerID"></span>
                    </label>
                    <select class="form-control" asp-for="ToCustomerID" asp-items="ViewBag.Customers">
                        <option value="">@Localizer["SelectCustomer"]</option>
                    </select>
                </div>

                <div class="col-md-6 form-group">
                    <label class="form-label">
                        @Localizer["TransferDate"]
                        <span class="text-danger fw-bold" asp-validation-for="TransferDate"></span>
                    </label>
                    <input class="form-control" asp-for="TransferDate" />
                </div>

                <div class="col-md-12 my-2">
                    <button type="submit" class="btn btn-primary">@Localizer["TransferCarButton"]</button>
                </div>
            </div>
        </form>
    </div>
</section>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#FromCustomerID').change(function () {
                var customerId = $(this).val();
                if (customerId) {
                    $.ajax({
                        url: '/TransferCars/GetCarByCustomer?customerId=' + customerId,
                        type: 'GET',
                        success: function (data) {
                            $('#NumberPlate').val(data.NumberPlate);
                            $('#CarID').val(data.carID);
                        }
                    });
                } else {
                    $('#NumberPlate').val('');
                    $('#CarID').val('');
                }
            });
        });
    </script>
}